# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentManager < Formula
  desc "Manage AI agent configurations across Claude Code and Codex"
  homepage "https://github.com/gstark/agent-manager"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.5/agent-manager_0.1.5_darwin_amd64.tar.gz"
      sha256 "da9ba22a681c557a12807a7c300f136971687d86f41c03d0274730078cc5830d"

      define_method(:install) do
        bin.install "agm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.5/agent-manager_0.1.5_darwin_arm64.tar.gz"
      sha256 "fd0c4af6029e1c6d9fc768457572043e475c5caeabf1a6a2d575cd5233d0ce74"

      define_method(:install) do
        bin.install "agm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.5/agent-manager_0.1.5_linux_amd64.tar.gz"
      sha256 "2dae36fe468843591c6520965b03da0abb8cdeb9567bd382a7d2054a6184e099"
      define_method(:install) do
        bin.install "agm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.5/agent-manager_0.1.5_linux_arm64.tar.gz"
      sha256 "b0b79c579b31ed7d76288f00f387cd058e77dec36cc3f6bdba3ca897276cf0d8"
      define_method(:install) do
        bin.install "agm"
      end
    end
  end
end
