# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentManager < Formula
  desc "Manage AI agent configurations across Claude Code and Codex"
  homepage "https://github.com/gstark/agent-manager"
  version "0.1.22"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.22/agent-manager_0.1.22_darwin_amd64.tar.gz"
      sha256 "bfeee8d8ad4f52f60f225a44e77e97460cc01d23302ccce5159a91da8f2ecf81"

      define_method(:install) do
        bin.install "agm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.22/agent-manager_0.1.22_darwin_arm64.tar.gz"
      sha256 "1e13aa32265b41253b004a4054b13311cb37e4e13b57237057c4895e058225ac"

      define_method(:install) do
        bin.install "agm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.22/agent-manager_0.1.22_linux_amd64.tar.gz"
      sha256 "c513a1a46f32f2203878f47db27b5dfc6823730ff652695b5c34c695ea5f8048"
      define_method(:install) do
        bin.install "agm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.22/agent-manager_0.1.22_linux_arm64.tar.gz"
      sha256 "6ab47e3faeba05a6a84aba5a107212b1d484e8d3af4ecbaae2f4c6db2c7f4459"
      define_method(:install) do
        bin.install "agm"
      end
    end
  end
end
