# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentManager < Formula
  desc "Manage AI agent configurations across Claude Code and Codex"
  homepage "https://github.com/gstark/agent-manager"
  version "0.1.24"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.24/agent-manager_0.1.24_darwin_amd64.tar.gz"
      sha256 "d23eba1138d0ee8c804310841ceb9938e65b88a9c6bd820c8e4291ec5ef9c03d"

      define_method(:install) do
        bin.install "agm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.24/agent-manager_0.1.24_darwin_arm64.tar.gz"
      sha256 "fe118e4e63cc64f8f1e935c4b96b176fb17d7b65d9fc1a56698b69a75926d42c"

      define_method(:install) do
        bin.install "agm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.24/agent-manager_0.1.24_linux_amd64.tar.gz"
      sha256 "d3c4171f03480ce65d749091496319501a4f4ddd9b59a5832793d18331c90573"
      define_method(:install) do
        bin.install "agm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gstark/agent-manager/releases/download/v0.1.24/agent-manager_0.1.24_linux_arm64.tar.gz"
      sha256 "f11f39f763cdff9b12d6629c11c445599cec00a8649918465d5a8d0724c877e5"
      define_method(:install) do
        bin.install "agm"
      end
    end
  end
end
